name: Generate effect icon.json

on:
  push:

jobs:
  generate-effect-font:
    name: generate-effect-font
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup minimum typescript code runner
        run: |
            npm i -g ts-node
            npm i -D @types/node
            echo '{"compilerOptions": {"target": "ESNext", "esModuleInterop": true}}' > tsconfig.json

      - name: Generate effect icon.json
        run: ts-node ./.github/workflows/generate_effect_icon_json.ts
        env:
          CHECKOUT_PATH: ${{ github.workspace }}

      - name: Commit changes
        run: |
          git_changes=$(git status --porcelain assets/minecraft/font/effect/icon.json assets/minecraft/font/effect/inline/icon.json)
          
          if [[ -z "$git_changes" ]]; then
            echo "No changes to commit in the font files"
            exit 0
          else
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git add assets/minecraft/font/effect/icon.json
            git add assets/minecraft/font/effect/inline/icon.json
            git commit -m "generate effect font json file"
            git push origin HEAD
          fi
